 Sayılardan oluşan bir boyutlu array oluşturulur. Arrayi oluştururken sayıların veri tipini integer olarak belirtilir. Oluşturulan arrayin boyut, eleman sayısı bilgilerine bakılır. 

In [2]:
import numpy as np

In [3]:
array = np.array([1,2,3,4,5,6], dtype=int)
print(array)

[1 2 3 4 5 6]


In [4]:
boyut = array.ndim
print("array boyutu",boyut)

eleman_sayisi = array.size
print("array eleman sayisi",eleman_sayisi)

array boyutu 1
array eleman sayisi 6


 İki ve üç boyutlu arrayler oluşturulur. Bu arraylerin boyut, eleman sayısı, satır, sütun bilgilerine ulaşılır. Arrayler üzerinde indexleme ve dilimleme(slicing) işlemi yapılır. 

In [5]:
# iki boyutlu array
array2 = np.array([[1,2,3], [4,5,6]])
print("array2 boyutu", array2.ndim)       #boyut
print("array2 eleman sayisi",array2.size) #eleman sayisi
satir, sutun = array2.shape               #satir ve sutun
print(f"satir {satir}, sutun {sutun}")

array2 boyutu 2
array2 eleman sayisi 6
satir 2, sutun 3


In [6]:
# uc boyutlu array
array3 = np.array([[[1,2,3], [4,5,6]] , [[7,8,9], [10,11,12]]])
print("array3 boyutu", array3.ndim)       #boyut
print("array3 eleman sayisi",array3.size) #eleman sayisi
derinlik, satir, sutun = array3.shape     #derinlik, satir ve sutun
print(f"derinlik {derinlik}, satir {satir}, sutun {sutun}")

array3 boyutu 3
array3 eleman sayisi 12
derinlik 2, satir 2, sutun 3


In [19]:
###indexleme###
#1.satirdaki 2. elemana ulasalim
print(array2[0,1])

#1.katmandaki 2.satirdaki 3. elemana ulasalim
print(array3[0,1,2])

2
6


In [20]:
###dilimleme###
#array2'de 4 ve 5 sayilarina ulasalim
print(array2[1, 0:2])

#array3'te 7 ve 10 sayilarina ulasalim
print(array3[1,0:2,0])

[4 5]
[ 7 10]


 Numpy fonksiyonu kullanarak bir, iki ve üç boyutlu arrayler oluşturulur. Arrayler üzerinde indexleme ve dilimleme(slicing) işlemi yapılır 

In [21]:
# bir boyutlu array
arr = np.arange(7)
print(arr)
# iki boyutlu array
arr2 = np.array([["a","b","c"], ["d","e","f"]])
print(arr2)
# uc boyutlu array
arr3 = np.array([[["q",2,6], [5,"f",3]] , [[4,8,5], [10,0,"b"]]])
print(arr3)

[0 1 2 3 4 5 6]
[['a' 'b' 'c']
 ['d' 'e' 'f']]
[[['q' '2' '6']
  ['5' 'f' '3']]

 [['4' '8' '5']
  ['10' '0' 'b']]]


In [18]:
#arr 5
arr[5] 
print(arr[5])
#arr2 d
arr2[1,0]
print(arr2[1,0])
#arr3 b
arr3[1,1,2]
print(arr3[1,1,2])

5
d
b


In [17]:
#arr 3,4,5
print(arr[2:5])
#arr2 b ve c
print(arr2[0,1:])
#arr3 2 ve f
print(arr3[0,:,1])

[2 3 4]
['b' 'c']
['2' 'f']


Sıfırlardan oluşan ve birlerden oluşan iki tane iki boyutlu array oluşturulur. Bu arrayler satır ve sütun bazında birleştirilir. 

In [12]:
zeros_array = np.zeros((3,4), dtype="int")
print(zeros_array)
ones_array = np.ones((3,4), dtype="int")
print(ones_array)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [22]:
#satir bazinda birlestirme
np.concatenate([zeros_array,ones_array], axis=0)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [23]:
#sutun bazinda birlestirme
np.concatenate([zeros_array,ones_array], axis=1)

array([[0, 0, 0, 0, 1, 1, 1, 1],
       [0, 0, 0, 0, 1, 1, 1, 1],
       [0, 0, 0, 0, 1, 1, 1, 1]])